### ISSUE TITLE
New pages for Mealplanner and found recipies

### ISSUE THREAD

**Issue by ikarrila** [ikarrila/COMP.SE.110-backend#36]
DoD:

Similarly to the Figma, we should have one page for applying filters and a separate one for showing and saving them

**Comment by BarryAlanPan** [comment]
![CleanShot 2024-11-08 at 10 09 24@2x](https://github.com/user-attachments/assets/bc1f23ca-678b-4deb-ba2f-3e88a837c75a)
Meal Planner page implemented, with params passed from homepage shown as included ingredients. Sliders are double-handled with default selection based on real situation.
